const char *EndingMessage =
  u8"जो सो रहा हो उसे तो जगा सकते हैं, लेकिन जो आँखे मूँद कर सोने का अभिनय कर रहा हो उसे कैसे जगाएंगे |\n"
  u8"You can wake one who is sleeping, but not one who is pretending to sleep.\n"
  u8"જે ઉંઘે છે એને જગાડી શકાય, પર જે ઉંગવાનો ઢોંગ કરે છે એને નહિ।\n"
  u8"Μπορείς να ξυπνήσεις κάποιον που κοιμάται, αλλά όχι κάποιον που προσποιείται ότι κοιμάται.\n"
  u8"يُمكِنُكَ أَن تُوقِظَ مَن هُوَ نَائِم، لَكنَّكَ لَنْ تُوقِظَ مَن هُوَ مُتَظَاهِرٌ بِالنَّوم.\n"
  u8"자는 사람은 깨울 수 있어도, 자는 척 하는 사람은 깨울 수 없다.\n"
  u8"Se puede despertar a alguien que duerme, pero no a alguien que pretende dormir.\n"
  u8"Tu peux réveiller celui qui dort, mais pas celui qui prétend dormir.\n"
  u8"תּוּכַל לְהָעִיר אָדָם יָשָׁן, אַךְ לֹא תּוּכַל לְהָעִיר אָדָם הַמַּעֲמִיד פְּנֵי יָשָׁן.\n"
  u8"ಮಲಗಿರುವನನ್ನು ಎಬ್ಬಿಸಬಹುದು. ಮಲಗುವ ನೆಪ ಮಾಡುವನನ್ನು ಎಬ್ಬಿಸಲಾಗದು.\n"
  u8"Sie können jemanden wecken, der schläft, aber nicht einen, der bloß vortäuscht zu schlafen.\n"
  u8"Você pode acordar alguém que está dormindo, mas não alguém que finge estar dormindo.\n"
  u8"Можно разбудить того кто спит, но не того кто притворяется спящим.\n"
  u8"Можеш да пробудиш оног који спава, али не оног који се претвара да спава.\n"
  u8"Možeš probuditi onog koji spava, ali ne onog koji se pretvara da spava.\n"
  u8"Îl poți trezi pe omul care doarme, dar nu și pe cel care se preface că doarme.\n"
  u8"Du kan väcka den som sover, men inte den som låtsas sova.\n"
  u8"Si può svegliare chi dorme, ma non chi fa finta di dormire.\n"
  u8"Felébresztheted azt, aki alszik, de azt nem, aki csak úgy tesz, mintha aludna.\n"
  u8"Spiaceho človeka môžete zobudiť, ale toho, ktorý spánok predstiera, nie.\n"
  u8"Може да събудиш спящия, но не и този, който се преструва.\n"
  u8"اپ سونے والے کو جگآ سکتے ہیں، جو سونے کا بہانہ کر رہا ہے، اسے نہیں\n"
;
